### ISSUE TITLE
doc.deno.land doesn't work well with mod.ts

### ISSUE THREAD

**Issue by crookse** [drashland/drash#547]
## Summary

I'm not sure what's going on with doc.deno.land, but an error occurs. We might need to reach out to the Deno team to figure out what's going on.

## Steps To Reproduce The Bug

1. Go to https://doc.deno.land/https/deno.land/x/drash/mod.ts
2. See the error.

It's only with`mod.ts` (i think) though. For example, look at `server.ts` here: https://doc.deno.land/https/deno.land/x/drash/src/http/server.ts

## Expected Behavior

The docs should show our files.

## Suggested Solution(s)

Work with the Deno team to figure out a solution. However, they're probably busy, so we might need to do debugging on our side.

**Comment by ebebbington** [comment]
The doc page is now fixed again, guessing it was due to them rewriting the site
