### ISSUE TITLE
ETag middleware

### ISSUE THREAD

**Issue by ebebbington** [drashland/drash#559]
Original issue:  https://github.com/drashland/deno-drash/issues/17

Ported over here because @crookse decided to make it a middleware instead (which is a good call), because it means it's usuable by users, but doesn't affect drash's performance at all - win win scenario

**What**

Add a new middleware for supporting the ETag header

**Why**

* Improves caching = improves request speed
* Will not affect Drash's performance because Drash wouldn't have it built into the source code

**How**

* File structure would look like:
```
deno-drash-middleware/
    etag/ <-- etag code here
        tests/
        deps.ts
        some_related_file.ts
        another_related_file.ts
        mod.ts
        README.md
    ...
```
* Users would import the middleware like:

`import { ETag } from "https://deno.land/x/drash-middleware@v{version}/etag/mod.ts"`

* Place third-party modules in your middleware directory's deps.ts file (if used)

* Any Deno std module that's required by your package can be exported from the repo's root deps.ts file so that all middleware can import std modules from that single file.

**Acceptance Criteria**

- [ ] README.md file showing how to use the middleware. Drash is a documentation-driven codebase, so the documentation is very important.

- [ ] Develop ETag functionality

- [ ] Tests

**Comment by ebebbington** [comment]
@diveDylan have you made any progress on this?

**Comment by diveDylan** [comment]
> @diveDylan have you made any progress on this?

sorry, i forget this!  I will join the discord and read contributing line. It is too late ...
