### ISSUE TITLE
Sass Compiler Middleware

### ISSUE THREAD

**Issue by ebebbington** [drashland/drash#566]
## Summary

What: Develop a middleware that will compile sass, an "on-the-go sass compile". It would check if the request is for a scss file -> compile to css -> respond back with css

A unique name could be thought of as well :)

Why: A really cool idea, that i definitely see benefits for (ie the extra utility for users)

## Acceptance Criteria

Use the contributing guidelines to aid in the development

- [ ] Develop the middleware
- [ ] Tests for every case/scenario
- [ ] It's own readme (`./<middleware>/REAMDE.md`)
- [ ] Follow the contributing guidelines

**Comment by crookse** [comment]
closing this. this can be written as documentation -- showing users how to precompile sass during compile time and how to serve that sass on requests
