### ISSUE TITLE
API Reference page fails to load

### ISSUE THREAD

**Issue by Sembiance** [drashland/drash#580]
## Summary

The API Reference URL linked to in the docs fails to load.

## Steps To Reproduce The Bug

1. Visit API Reference page: https://doc.deno.land/https/deno.land/x/drash/mod.ts
2. See error message: `An unexpected error has occurred.`

**Comment by ebebbington** [comment]
Duplicate of #547, thanks @Sembiance but this issue is dependant on Deno, nothing we can do at the moment :/

**Comment by ebebbington** [comment]
@Sembiance if you needed the documentation for a specific class or method, feel free to let me know and i can supply it manually

**Comment by Sembiance** [comment]
> @Sembiance if you needed the documentation for a specific class or method, feel free to let me know and i can supply it manually

Thanks, but I'm all set.
