### ISSUE TITLE
Allow to pass status code into response methods

### ISSUE THREAD

**Issue by ebebbington** [drashland/drash#583]
eg `response.json({ name: 'drash' }, 200)` or `response.text("Invalid request", 200)`

```ts
declare function <name>(param1: unknown, status = 200): void
```

**Comment by ebebbington** [comment]
found whilst working on realworld, would be great to not have to add an extra line to specify status code

**Comment by crookse** [comment]
should we just overloaded methods? i ask because what if we end up wanting to add headers easily

**Comment by ebebbington** [comment]
@crookse it's a good idea actually, but im generally against overloads cause the main function gets messy, like what if we then wanna add something else?

```ts
text(text: string, status = 200): void

text(text: string, headers = []): void

text(text: string, status = 200, headers = [])

text(text: string, param?: number | string[]) {
  if
  if
  if
  if
```

duplicate that for each response method, what ive actually been thinking about instead after reading your comment, is something like

```ts
text(text: string, status = 200, headers = []) {
  this.setResponse(text, status, headers)
}
json(json: object, status = 200, headers = []) {
  this.setResponse(JSON.stringify(json), status, headers)
}
...
#setResponse(body: BodyInit | null, status = 200, headers = []) {
  this.status = status
  if (headers.length) {
    headers.forEach(h => this.headers.set(h.name, h.value))
  }
  tis.body = body
}
```

what are your thoughts? if you feel storngly about overloads then we can try it out

**Comment by crookse** [comment]
nah i don't have a preference. just thought overloads would make it easier.
