### ISSUE TITLE
Uncaught ReferenceError: URLPattern is not defined

### ISSUE THREAD

**Issue by bobwatcherx** [drashland/drash#585]
deno spec
deno 1.14.0 (release, x86_64-unknown-linux-gnu)
v8 9.4.146.15
typescript 4.4.2

`// app.ts

// Replace `<VERSION>` with the latest version of Drash v2.x. The latest
// version can be found at https://github.com/drashland/drash/releases/latest
import * as Drash from "https://deno.land/x/drash/mod.ts";

// Create your resource

class HomeResource extends Drash.Resource {
  public paths = ["/"];

  public GET(request: Drash.Request, response: Drash.Response): void {
    return response.json({
      hello: "world",
      time: new Date(),
    });
  }
}

// Create and run your server

const server = new Drash.Server({
  hostname: "0.0.0.0",
  port: 1447,
  protocol: "http",
  resources: [HomeResource],
});

server.run();

console.log(`Server running at ${server.address}.`);`

error :
error: Uncaught ReferenceError: URLPattern is not defined
        patterns.push(new URLPattern({ pathname: path + "{/}?" }));
                          ^
    at https://deno.land/x/drash@v2.2.0/src/http/server.ts:111:27
    at Array.forEach (<anonymous>)
    at https://deno.land/x/drash@v2.2.0/src/http/server.ts:109:22
    at Array.forEach (<anonymous>)
    at new Server (https://deno.land/x/drash@v2.2.0/src/http/server.ts:106:29)
    at file:///home/bob/belajarweb/denoPro/ant/app.ts:22:16

**Comment by crookse** [comment]
hey @bobwatcherx , just run `deno upgrade` and you should be good to go.

**Comment by crookse** [comment]
actually. your deno version is when they introduced URLPattern. caching issue maybe? i would 1. upgrade to latest deno and 2. kill your deno cache

**Comment by ebebbington** [comment]
I think it was unstable in 1.14 and stable in 1.15 or 1.16? So you are right Eric, an upgrade should fix it

**Comment by crookse** [comment]
@bobwatcherx did an upgrade work?

**Comment by bobwatcherx** [comment]
It work . Good thanks

**Comment by ebebbington** [comment]
will close this now
