### ISSUE TITLE
Throw JSON Response

### ISSUE THREAD

**Issue by mdanialr** [drashland/drash#594]
## Summary

What is your question?
is it possible to throw JSON response rather than HTTP (just like what's written in the docs)?

```
  /**
   * Run this service before the POST, PATCH|PUT HTTP method.
   */
  public runBeforeResource(req: Dr.Request, _: Dr.Response): void {
    const param = req.bodyParam<string>("params");
    if (!param) {
      throw new Dr.Errors.HttpError(400, "params field is required!");
    }
  }
```
this indeed cut the chaining request and throw an error but it throws HTTP instead.
I already tried this
```
  /**
   * Run this service before the POST, PATCH|PUT HTTP method.
   */
  public runBeforeResource(req: Dr.Request, res: Dr.Response): void {
    const param = req.bodyParam<string>("params");
    if (!param) {
      res.status = 400;
      return res.json({
        messages: ["params field is required!"],
      });
    }
  }
```
but this snippet doesn't cut the chain and still continues the request cycle to the resource.
how do i cut the request cycle and return a JSON response instead?

Thank you.

**Comment by crookse** [comment]
there's currently work being done in #592 to address this. we stripped out the error handling logic when we introduced v2. the current workaround is to NOT throw an error, but to return a response in a resource (again, sorry this not as flexible as a service):

```typescript
import * as Drash from "https://deno.land/x/drash@v2.3.0/mod.ts";

class MyResource extends Drash.Resource {
  public paths = ["/"];

  public POST(req: Drash.Request, res: Drash.Response): void {
    const param = req.bodyParam<string>("params");

    if (!param) {
      res.status = 400;
      return res.json({
        errors: [
          "Field `params` is required."
        ]
      });
    }
  }
}

// Create your server and plug in dexter to the middleware config
const server = new Drash.Server({
  resources: [
    MyResource,
  ],
  hostname: "0.0.0.0",
  port: 1447,
  protocol: "http",
});

server.run();

console.log(`Server running at ${server.address}`);
```

also, to make returning responses a bit more intuitive, https://github.com/drashland/drash/issues/583 is in quarter 1 as well

**Comment by mdanialr** [comment]
will [#592](https://github.com/drashland/drash/pull/592) be merged to v2 soon after got approved? so i could try it out?

**Comment by crookse** [comment]
hey @mdanialr, v2.4.0 was released (includes #592). the documentation page for error handling can be found here: https://drash.land/drash/v2.x/tutorials/servers/error-handling

let us know if you have any questions or if the documentation is not clear. happy coding! (also, let me know if i'm good to close this issue)

**Comment by mdanialr** [comment]
@crookse that's great! also thanks for your notes

**Comment by crookse** [comment]
hey @mdanialr , i decided to improve on the error handling page and include an example on throwing errors in services (inspired by this issue). the documentation is currently in a pull request, but you can view the documentation at http://localhost:3000/drash/v2.x/tutorials/servers/error-handling under the Throwing Errors in Services section
