### ISSUE TITLE
e.code check in request handler doesn't account for non-HTTP error objects with code property

### ISSUE THREAD

**Issue by crookse** [drashland/drash#595]
See https://github.com/drashland/drash/pull/592#discussion_r777265454

Our error handling process assumes that any error object thrown that contains a code field will be a correct HTTP status code. this needs to be fixed because some dependencies can throw an error in a service or resource AND have a code field that IS NOT an HTTP status code.

we need to ensure that if the code field is present, that it is a correct HTTP status code. otherwise, make it a 500.

also, if the code field is not present, then set it to 500 (as it does currently)

**Comment by Guergeiro** [comment]
![image](https://user-images.githubusercontent.com/39097691/148315885-ac717076-179f-4fc7-97d7-9df0e2af4d63.png)

Print for context, since I can't see it correctly with link.

**Comment by routmoute** [comment]
the question is answered here: https://github.com/drashland/drash/pull/592#discussion_r780366526
