### ISSUE TITLE
`Response#file()` doesnt work on images

### ISSUE THREAD

**Issue by ebebbington** [drashland/drash#599]
Only tested on a jpg file, the code passes, no errors thrown, but the way we're reading **image** files is incorrect

The code needs to be `readFileSync`, not `readTextFileSync`

Tested myself and changing it still correctly displays js, css etc, but also will display pngs and jpgs

![image](https://user-images.githubusercontent.com/47337480/151033162-d784b30e-6b4a-4617-b166-fec829806a92.png)

Basic fix, but dont think we can properly test this, unless there's a way to know if a binary is readable? eg

```
test(() => {
  response.file('image.jpg')
  const body = response.body
  const isReadable = maybeSomeThirdPartyModule(body) // expected: true
})
```

**Comment by crookse** [comment]
interesting. we could add a try catch to gracefully handle the error in case the file isn't readable, but should we?

**Comment by ebebbington** [comment]
> interesting. we could add a try catch to gracefully handle the error in case the file isn't readable, but should we?

Would make sense but I think our beautiful lifecycle would already catch it and throw a http error

**Comment by ebebbington** [comment]
The only test needed is that file() produces a binary, which it does now

If images/files are invalid, ie the content of the file, thats down to the user check and fix?
