### ISSUE TITLE
Allow services to send repsonses and end lifecycle

### ISSUE THREAD

**Issue by ebebbington** [drashland/drash#605]
## Summary

Im sure we added something like this before, not sure what happened

What:

For example allow a service before resource to redirect, and not have the resource called

Why:

A real use case people have

**Comment by crookse** [comment]
yea you had logic to handle this right before we released v2. it was the `send` prop and `end()` method on the service that I said we didn't need to use. good thing those data members are still in the service class though lol. my bad!
