### ISSUE TITLE
Resource paths should be sorted as they're defined

### ISSUE THREAD

**Issue by crookse** [drashland/drash#609]
## Summary

There was a bug in v1 where paths with wildcards would supersede paths that were "real". Breno has a good description of what should be happening:

> The slug is a path parameter, right? Maybe if we can prioritize "real paths" and push the others to the end, then we would always try to match a "perfect" path and only after try to match the others.

**Comment by ebebbington** [comment]
I dont think this is the case in v2

```ts
class Res extends Resource {
  paths = ["/*"];

  public GET(r: Request, response: Response) {
    response.text("all");
  }
}

class Res2 extends Resource {
  paths = ["/users/:username"];

  public GET(r: Request, response: Response) {
    response.text("hello ed");
  }
}

const server = new Server({
  resources: [
    Res,
    Res2
  ],
  protocol: "http",
  hostname: "localhost",
  port: 3000,
});

server.run();
```
`GET` to `/users/d` will use `Res2`

**Comment by crookse** [comment]
Pretty sure this has been working as expected. Closing. Def not the case in v3.
