### ISSUE TITLE
Issue using download method downloads the file with `download` name

### ISSUE THREAD

**Issue by sant123** [drashland/drash#611]
## Summary

Running this code https://drash.land/drash/v2.x/tutorials/responses/setting-the-body#download from the docs always generates a file named `download`.

## Steps To Reproduce The Bug

1. Copy and paste the code from the docs
2. Run the app
3. Open a browser tab with the application link
4. Will see all files downloaded as `download`

## Expected Behavior

It should use the filename from the function parameters

## Suggested Solution(s)

The issue is in the `Content-Disposition` header

## Screenshots

![image](https://user-images.githubusercontent.com/7959437/155070250-b4bed317-dc3d-4b96-bb4c-83c656ec6f57.png)

**Comment by ebebbington** [comment]
Thanks for raising this issue, we’ll try get to it some point this week 👌
