### ISSUE TITLE
bodyParam returns undefined for null-value params

### ISSUE THREAD

**Issue by sanekb** [drashland/drash#623]
`bodyParam` returns `undefined` for param_names that actually set to `null` in application/json post-request
at the same time correct value can be obtained by calling `bodyAll()[param_name]`

e.g.
```ts
request.bodyAll()           // { foo: null }
request.bodyAll()['foo']    // null
request.bodyParam('foo')    // undefined
```

is the `bodyParam` function currently behaving correctly?
```ts
// src/http/request.ts#L132
return this.#parsed_body![name] as unknown as T ?? undefined;
```

**Comment by crookse** [comment]
hi @sanekb , this seems like a bug. thanks for bringing this up! we'll investigate this and get back to you.
