### ISSUE TITLE
feat: add connInfo to IErrorHandler?

### ISSUE THREAD

**Issue by biluohc** [drashland/drash#653]
## Summary

What: add connInfo to IErrorHandler

Explain what the feature is
```ts
// give a Drash.Request with ConnInfo and empty pathParams
class MyErrorHandler extends Drash.ErrorHandler {
  public catch(
    error: Error,
    request: Drash.Request,
    response: Drash.Response,
  ): void {
    const ci = request.conn_info;
}

// Or add an argumnet
class MyErrorHandler extends Drash.ErrorHandler {
  public catch(
    error: Error,
    request: Request,
    response: Drash.Response,
    connInfo: ConnInfo,
  ): void {}
```

Why: My ErrorHandler needs the ConnInfo

Explain why this feature should be implemented

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] {add more checkboxes required by this issue as needed}

## Example Pseudo Code (for implementation)

```typescript
// Add example pseudo code for implementation
```

**Comment by Guergeiro** [comment]
Hello @biluohc and thank you for opening this issue.

Before we start talking about implementation details for this feature, could you explain better what you need from Drash that it's not being fulfilled?

**Comment by ebebbington** [comment]
Just like how we do when creating a request, we pass in the connInfo, so maybe we just expose this for the error handler too
